/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendita.Productos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import tiendita.Beans.Bean;
import tiendita.Borrado.Eliminar;
import tiendita.Conexiones.conexion;
import tiendita.Guardado.Actualizar;
import tiendita.Guardado.Guardar;

/**
 *
 * @author Mikaela Estefania Ramirez Herrera <Estefania_mikaela@hotmail.com>
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        setTitle("Modificar datos");
        TP();
        Llenar();
    }
    Bean bean = new Bean();
    Guardar guardar = new Guardar();
    Actualizar update = new Actualizar();
    Eliminar del = new Eliminar();
    DefaultTableModel model;
    static Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Um1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        precio1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Cantidad1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Cb1 = new javax.swing.JCheckBox();
        Cb2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarKeyTyped(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 150, -1));

        main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Producto"
            }
        ));
        main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(main);
        if (main.getColumnModel().getColumnCount() > 0) {
            main.getColumnModel().getColumn(0).setMinWidth(100);
            main.getColumnModel().getColumn(0).setPreferredWidth(100);
            main.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 560, 190));

        jLabel4.setText("Buscar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 20));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, 20));

        jLabel12.setText("U. medida");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        Um1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "1 KG", "1/2 KG", "1/4 KG", "1 LT", "1/2 LT", "1/4 LT", "Caja", "Reja", "Docena" }));
        jPanel1.add(Um1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel13.setText("Precio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 70, 20));

        jLabel5.setText("$");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLabel14.setText("Cantidad en almacen");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        Cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cantidad1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 80, -1));

        jLabel15.setText("Incluir");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        Cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(Cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));
        jPanel1.add(Cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Modificar inventario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 140, 30));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyPressed

    }//GEN-LAST:event_BuscarKeyPressed

    private void mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMouseClicked
        int fil = main.getSelectedRow();
        if (fil >= 0) {
            bean.setId(Integer.parseInt(main.getValueAt(fil, 0).toString()));
            Encontrar();
            JOptionPane.showMessageDialog(null, main.getValueAt(fil, 1).toString() + " Seleccionado");
        } else {
            JOptionPane.showMessageDialog(null, "No Se A Seleccionado Una Fila");
        }
    }//GEN-LAST:event_mainMouseClicked

    private void Cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cantidad1ActionPerformed

    private void Cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((!Cb1.isSelected()) && (!Cb2.isSelected())) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una opcion");
        } else {
            if (Cb1.isSelected()) {
                bean.setCase1("`Producto`= '" + nombre.getText() + "'");
                guardarNom(bean.getId(), bean.getCase1());
                JOptionPane.showMessageDialog(null, "Cambios Guardados");
                nombre.setText("");
                TP();
            }
            if (Cb2.isSelected()) {
                bean.setCase2("`UID1`= '" + Um1.getSelectedIndex() + "', `Um1`= '" + Um1.getSelectedItem().toString() + "',`P1`='" + precio1.getText() + "',`C1`='" + Cantidad1.getText() + "'");
                guardarInv(bean.getId(), bean.getCase2());
                JOptionPane.showMessageDialog(null, "Cambios Guardados");
                Cb2.setSelected(false);
                Um1.setSelectedIndex(0);
                precio1.setText("");
                Cantidad1.setText("");
                nombre.setText("");
                TP();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarKeyTyped
        bean.setNombre(Buscar.getText());
        TB();
    }//GEN-LAST:event_BuscarKeyTyped

    public void TP() {
        cargar();
    }

    public void TB() {
        buscarcargar();
    }

    private void cargar() {
        clear();
//        titulos();
        String[] registros = new String[3];
        TableColumnModel columnModel = main.getColumnModel();
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `inventario` ORDER BY Producto ASC");
            while (rs.next()) {
                registros[0] = rs.getString("Id");
                registros[1] = rs.getString("Producto");
//                registros[2] = "$ " + rs.getString("precio");
                model.addRow(registros);
            }
            main.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void buscarcargar() {
        clear();
//        titulos();
        String[] registros = new String[3];
        TableColumnModel columnModel = main.getColumnModel();
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `inventario` where producto LIKE '" + bean.getNombre() + "%" + "'");
            while (rs.next()) {
                registros[0] = rs.getString("id");
                registros[1] = rs.getString("producto");
//                registros[2] = "$ " + rs.getString("precio");
                model.addRow(registros);
            }
            main.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
        private void Llenar(){
    Um1.removeAllItems();
        String[] registros = new String[5];
        try {
            con = conexion.getConnection();
            String query = "SELECT * FROM `medidas`";
            Statement ps = con.createStatement();
            ResultSet rs = ps.executeQuery(query);
            while (rs.next()) {
                Um1.addItem(rs.getString("Um"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println(ex);
        }
    }

//    private void titulos() {
//        try {
//            con = conexion.getConnection();
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery("SELECT * FROM `inventario`");
//            while (rs.next()) {
//                //Para obtener esta información, hay que pedirle los MetaDatos al ResulSet.
//                ResultSetMetaData metaDatos = rs.getMetaData();
//                // Se obtiene el número de columnas.
//                int numeroColumnas = metaDatos.getColumnCount();
//                // Se crea un array de etiquetas para rellenar
//                Object[] etiquetas = new Object[numeroColumnas];
//                // Se obtiene cada una de las etiquetas para cada columna
//                for (int i = 0; i < numeroColumnas; i++) {
//                    // Nuevamente, para ResultSetMetaData la primera columna es la 1.
//                    etiquetas[i] = metaDatos.getColumnLabel(i + 1);
//                }
//                model.setColumnIdentifiers(etiquetas);
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }
//    }
    private void clear() {
        model = ((DefaultTableModel) main.getModel());
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    public void guardarInv(int id, String sql) {

        try {
            con = conexion.getConnection();
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            PreparedStatement ps = con.prepareStatement("UPDATE `inventario` SET " + sql + "  WHERE `Id`='" + id + "'"); //siempre poner el primer dato NULL
            int res = ps.executeUpdate();
            con.close(); //siempre cerrar las conexiones despues de usarlas
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex); // imprime el error si hay
        }
    }

    public void guardarNom(int id, String sql) {

        try {
            con = conexion.getConnection();
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            PreparedStatement ps = con.prepareStatement("UPDATE `inventario` SET " + sql + "  WHERE `Id`='" + id + "'"); //siempre poner el primer dato NULL
            int res = ps.executeUpdate();
            con.close(); //siempre cerrar las conexiones despues de usarlas
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex); // imprime el error si hay
        }
    }

    private void Encontrar() {
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `inventario` WHERE inventario.Id='" + bean.getId() + "' ORDER BY Producto ASC");
            while (rs.next()) {
                nombre.setText(rs.getString("producto"));
                Um1.setSelectedIndex(rs.getInt("UID1"));
                precio1.setText(rs.getString("P1"));
                Cantidad1.setText(rs.getString("C1"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    public static javax.swing.JTextField Cantidad1;
    public static javax.swing.JCheckBox Cb1;
    public static javax.swing.JCheckBox Cb2;
    private javax.swing.JLabel Fondo;
    public static javax.swing.JComboBox<String> Um1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable main;
    private javax.swing.JTextField nombre;
    public static javax.swing.JTextField precio1;
    // End of variables declaration//GEN-END:variables
}
