/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendita;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tiendita.Conexiones.conexion;

/**
 *
 * @author Mikaela Estefania Ramirez Herrera <Estefania_mikaela@hotmail.com>
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        jScrollPane3.setVisible(false);
        TabEx.setVisible(false);
        cargar(plus);
        cargar3(plus);
        calendar.setTime(date);
        this.setExtendedState( JFrame.MAXIMIZED_BOTH );//maximizado
        this.toFront();
        this.getContentPane().setBackground(Color.white);
        TabVendedor.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 14));
        TabDatos.getTableHeader().setFont(new java.awt.Font("Tahoma", 0, 14));
    }
    DefaultTableModel model;
    DefaultTableModel model2;
    DefaultTableModel model3;
    static Connection con;
    Date date = new Date();
    Calendar calendar = Calendar.getInstance();
    int nwoy = calendar.get(Calendar.WEEK_OF_YEAR);
    DateFormat day = new SimpleDateFormat("dd");
    DateFormat month = new SimpleDateFormat("MM");
    DateFormat year = new SimpleDateFormat("yyyy");

    String SQL = "SELECT reporte_info.Id, usuarios.Nombre, `Total_Venta`,`Fecha`,`Hora`, reporte_venta.Producto, "
            + "reporte_venta.Presentacion, reporte_venta.TotalProducto, reporte_venta.Cantidad "
            + "FROM `reporte_info` "
            + "INNER JOIN usuarios on usuarios.IdUsuario= reporte_info.Id_vendedor "
            + "INNER JOIN reporte_venta on reporte_venta.Id_Info= reporte_info.Id ";
    String plus = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabVendedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Exportar = new javax.swing.JButton();
        filtro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabDatos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabEx = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vendedor", "Total Venta", "Fecha", "Hora"
            }
        ));
        TabVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabVendedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabVendedor);
        if (TabVendedor.getColumnModel().getColumnCount() > 0) {
            TabVendedor.getColumnModel().getColumn(0).setMinWidth(50);
            TabVendedor.getColumnModel().getColumn(0).setPreferredWidth(50);
            TabVendedor.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 820, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Imprimir Reporte de Ventas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        Exportar.setBackground(new java.awt.Color(0, 153, 102));
        Exportar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Exportar.setText("Exportar");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });
        jPanel1.add(Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 160, 40));

        filtro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Semana", "Mes", "Año", "Historia" }));
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        jPanel1.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        TabDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TabDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Presentacion", "Total por producto", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(TabDatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 820, 240));

        TabEx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Venta", "Vendedor", "Total Venta", "Fecha", "Hora", "Producto", "Presentacion", "Total por producto", "Cantidad"
            }
        ));
        TabEx.setOpaque(false);
        jScrollPane3.setViewportView(TabEx);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 80, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("@ADMINISTRADOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Eliminar Registros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 170, 40));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabVendedorMouseClicked
        int fil = TabVendedor.getSelectedRow();
        if (fil >= 0) {
            cargar2(Integer.parseInt(TabVendedor.getValueAt(fil, 0).toString()));
        } else {
            JOptionPane.showMessageDialog(null, "No Se A Seleccionado Una Fila");
        }
    }//GEN-LAST:event_TabVendedorMouseClicked

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        ToExcel.Exportar();
    }//GEN-LAST:event_ExportarActionPerformed

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        switch (filtro.getSelectedIndex()) {
            case 0:
                plus = "WHERE Dia='" + day.format(date) + "' AND Mes='" + month.format(date) + "' AND Año='" + year.format(date) + "'";
                cargar(plus);
                cargar3(plus);
                break;
            case 1:
                plus = "WHERE Semana='" + nwoy + "' AND Año='" + year.format(date) + "'";
                cargar(plus);
                cargar3(plus);
                break;
            case 2:
                plus = "WHERE Mes='" + month.format(date) + "' AND Año='" + year.format(date) + "'";
                cargar(plus);
                cargar3(plus);
                break;
            case 3:
                plus = "WHERE Año='" + year.format(date) + "'";
                cargar(plus);
                cargar3(plus);
                break;
            case 4:
                plus = "";
                cargar(plus);
                cargar3(plus);
                break;
        }
    }//GEN-LAST:event_filtroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DeleteAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargar(String plus) {
        clear();
//        titulos();
        String[] registros = new String[5];
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT reporte_info.Id, usuarios.Nombre, `Total_Venta`,`Fecha`,`Hora` FROM `reporte_info` "
                    + "INNER JOIN usuarios on usuarios.IdUsuario= reporte_info.Id_vendedor " + plus + "");
            while (rs.next()) {
                registros[0] = rs.getString("reporte_info.Id");
                registros[1] = rs.getString("usuarios.Nombre");
                registros[2] = "$ " + rs.getString("Total_Venta");
                registros[3] = rs.getString("Fecha");
                registros[4] = rs.getString("Hora");
                model.addRow(registros);
            }
            TabVendedor.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void cargar2(int id) {
        clear2();
//        titulos();
        String[] registros = new String[4];
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT `Producto`,`Presentacion`,`TotalProducto`,`Cantidad` FROM `reporte_venta` WHERE `Id_Info`= '" + id + "'");
            while (rs.next()) {
                registros[0] = rs.getString("Producto");
                registros[1] = rs.getString("Presentacion");
                registros[2] = "$ " + rs.getString("TotalProducto");
                registros[3] = rs.getString("Cantidad");
                model2.addRow(registros);
            }
            TabDatos.setModel(model2);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void cargar3(String plus) {
        clear3();
//        titulos();
        String[] registros = new String[9];
        try {
            con = conexion.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL + plus);
                registros[0] = "-";
                registros[1] = "-";
                registros[2] = "-";
                registros[3] = "-";
                registros[4] = "-";
                registros[5] = "-";
                registros[6] = "-";
                registros[7] = "-";
                registros[8] = "-";
                model3.addRow(registros);
            while (rs.next()) {
                registros[0] = rs.getString("reporte_info.Id");
                registros[1] = rs.getString("usuarios.Nombre");
                registros[2] = "$ " + rs.getString("Total_Venta");
                registros[3] = rs.getString("Fecha");
                registros[4] = rs.getString("Hora");
                registros[5] = rs.getString("reporte_venta.Producto");
                registros[6] = rs.getString("reporte_venta.Presentacion");
                registros[7] = "$ " + rs.getString("reporte_venta.TotalProducto");
                registros[8] = rs.getString("reporte_venta.Cantidad");
                model3.addRow(registros);
            }
            TabEx.setModel(model3);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void clear() {
        model = ((DefaultTableModel) TabVendedor.getModel());
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }

    private void clear2() {
        model2 = ((DefaultTableModel) TabDatos.getModel());
        while (model2.getRowCount() > 0) {
            model2.removeRow(0);
        }
    }

    private void clear3() {
        model3 = ((DefaultTableModel) TabEx.getModel());
        while (model3.getRowCount() > 0) {
            model3.removeRow(0);
        }
    }
    
        public void DeleteAll() {
int x = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todos los registros actuales?", "Elige una opcion", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            try {
                con = conexion.getConnection();
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                PreparedStatement ps = con.prepareStatement("TRUNCATE `pvdb`.`reporte_info`");
                int res = ps.executeUpdate();
                PreparedStatement ps2 = con.prepareStatement("TRUNCATE `pvdb`.`reporte_venta`");
                int res2 = ps2.executeUpdate();
            } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(Tiendita.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Toda la informacion fue eliminada");
        } else {
            JOptionPane.showMessageDialog(null, "Proceso Cancelado");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exportar;
    private javax.swing.JTable TabDatos;
    public static javax.swing.JTable TabEx;
    private javax.swing.JTable TabVendedor;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
